
# 1. Enable Google Auth
#    Go to Supabase Dashboard -> Authentication -> Providers.
#    Enable "Google".
#    You will need to set up a Google Cloud Project to get the Client ID and Secret.

# 2. Database Schema
#    Run this SQL in the Supabase SQL Editor:

create table activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  domain text not null,
  duration int not null,
  start_time timestamptz not null,
  created_at timestamptz default now()
);

# 3. Row Level Security (RLS) - "User Centric Data"
#    This ensures users can ONLY see their own data if querying directly.

alter table activity_logs enable row level security;

create policy "Users can view their own logs"
on activity_logs for select
using ( auth.uid() = user_id );

create policy "Service Role can insert logs"
on activity_logs for insert
with check ( true ); -- We trust our Node.js server (using Service Key) to insert correctly
